# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv',
            name='published_date',
        ),
        migrations.AddField(
            model_name='inv',
            name='hostname',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='inv',
            name='ip4address',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='inv',
            name='timeLoginInRDP',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
