# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20180813_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv',
            name='timeLoginInRDP',
        ),
    ]
