# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_remove_inv_timelogininrdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv',
            name='macaddress',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
