# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_inv_macaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv',
            name='loginInRDP',
            field=models.DateTimeField(null=True),
        ),
    ]
