# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20180813_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='loginInRDP',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
